### ISSUE TITLE
Small fix for debug builds in SharePlugin.gdip file. - Godot v4.2.2.stable 

### ISSUE THREAD

**Issue by TheOathMan** [cengiz-pz/godot-ios-share-plugin#2]
While testing the plugin in Godot v4.2.2.stable. the config File `SharePlugin.gdip` has the value of  binary to `binary="SharePlugin.release.a"` which causes link Error on Debug builds:

`Undefined symbols for architecture arm64: ClassDB::bind_methodfi(unsigned int, MethodBind*, bool, char const*, Variant const**, int)
`

Setting the value of binary to `binary="SharePlugin.a"` instead, let the Engine export `SharePlugin.debug.a` if the build is debug or `SharePlugin.release.a` if `Export With Debug` is uncheck. Which fixes this bug.

Just letting you know to see if this fix is Godot version specific or it's an actual bug in your implementation. Thank you :)

**Comment by cengiz-pz** [comment]
Hi @TheOathMan, I did not know that the engine did that.  I was managing it manually.  Thanks!
