### ISSUE TITLE
Undefined symbols: Object::get_argument_options

### ISSUE THREAD

**Issue by RedaMorsli** [cengiz-pz/godot-ios-share-plugin#4]
### Description
Xcode build for iOS fails and prints this error:
```
ld: warning: Could not find or use auto-linked framework 'AudioUnit': framework 'AudioUnit' not found
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
Undefined symbols for architecture arm64:
 "Object::get_argument_options(StringName const&, int, List<String, DefaultAllocator>*) const", referenced from:
     vtable for SharePlugin in SharePlugin.release.a[arm64][3](share_plugin_implementation.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The error is occurring in release and debug builds.

### Environment
- Godot official v4.3.stable
- Plugin v1.0
- System: macOS Sonoma 14.5
- Xcode v15.4 (15F31d)

**Comment by cengiz-pz** [comment]
Hi @RedaMorsli, please see https://github.com/cengiz-pz/godot-ios-share-plugin/issues/2#issue-2283595581 for a quick fix or use the 2.0 release that is coming in a couple of hours.

**Comment by cengiz-pz** [comment]
See #2.

**Comment by RedaMorsli** [comment]
The version 2.0 of the plugin is working correctly, thank you !
