### ISSUE TITLE
Not work on Godot 4.2.2

### ISSUE THREAD

**Issue by exorcius** [cengiz-pz/godot-ios-share-plugin#6]
Press share button but nothing happens. It seems Share Plugin has problem with initializing

**Comment by cengiz-pz** [comment]
Could you share your logcat output?

**Comment by cengiz-pz** [comment]
Could you share your Xcode logs?

**Comment by exorcius** [comment]
Oh sorry. I posted wrong place. I have problem with Android plugin. share_text work perfectly but share_image is not working. Logs do not show anything (Tested on Samsung Galaxy j4+ api 21)

**Comment by cengiz-pz** [comment]
Hi @exorcius, please close this issue, open a new issue on the [Android repo](https://github.com/cengiz-pz/godot-android-share-plugin), and attach a zipped minimal project that reproduces your issue, but exclude the export template and the plugin in the zip.
